### ISSUE TITLE
Receiving 400 error from Notion

### ISSUE THREAD

**Issue by asachs01** [lobre/pocket2notion#1]
Howdy 👋 looks like following the readme I get a 400 from Notion:

```
pocket2notion --notion-tags=false  MY_NOTION_BLOCK_ID
...
Pushing batch into Notion
wrong return value from Notion: 400
```

Not sure if there's a way to get some more verbose output, but seems like this may be generating a bad request to notion?

**Comment by asachs01** [comment]
Ah, nvm. I was pulling the wrong value for the block id. Works flawlessly!

**Comment by lobre** [comment]
Glad it still works!
